export const ActionTypes = {
    LIST_USER: 'LIST_USER',
    LIST_PRODUCTS:'LIST_PRODUCTS',
    LIST_CATEGORIES:'LIST_CATEGORIES',
    REGISTER_USER: 'REGISTER_USER',
    FRGTPSWRD_USER: 'FRGTPSWRD_USER'
}